name: CI

on:
  push:
    branches: [ main ]
jobs:
  example-1:
    name: Ex1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Conda info
        shell: bash -l {0}
        run: conda info
