name: CI

on:
  push:
    branches: [ main ]

jobs:
  example-3:
    name: Ex3 Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          python-version: 3.5
          auto-activate-base: false
      - run: |
          conda info
          conda list
